name = "ekhlasi-amlak"
main = "src/index.js"
compatibility_date = "2024-12-18"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "KV"
id = "e821eeeb163344c9a253f9af10139716"

[vars]
GITHUB_TOKEN = "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"
GITHUB_REPO = "ekhlasi1/real-estate-panel"
GITHUB_BRANCH = "main"